apiVersion: v1
kind: Secret
metadata:
  labels:
    app: postgresql
  name: postgresql
stringData:
  database-name: gamedb
  database-password: 2WEeyPUrMNeB6sqE
  database-user: demo     -p POSTGRESQL_PASSWORD=password!     -p POSTGRESQL_DATABASE=gamedb
